###
GET http://localhost:3000/api/tasks

###
POST http://localhost:3000/api/tasks
Content-Type: application/json

{
    "title": "Hacer un sitio web en Laravel",
    "description": "Trabajo freelance",
    "done": true
}

###
GET http://localhost:3000/api/tasks/5fea65ab2bd1fc4770730dd7asdasdasdsa

###
DELETE http://localhost:3000/api/tasks/5aeaa4249c2b1b6f64bac5b1

###
GET http://localhost:3000/api/tasks/done

###
PUT http://localhost:3000/api/tasks/5fea5b0913c2a5353bbbce78
Content-Type: application/json

{
    "title": "Crear un sitio web en Wix"
}